image:
  name: composer:2.5

pipelines:
  default:
    - step:
        script:
          - PATH=$PATH:$PWD
          - composer validate
          - composer install
          - vendor/bin/phpunit --log-junit ./test-reports/junit.xml
